### ISSUE TITLE
🐛 Pre-prod alertmanager not running (3000+ restarts)

### ISSUE THREAD

**Issue by wanieldilson** [ministryofjustice/staff-infrastructure-monitoring-deployments#93]
**Describe the bug**
When monitoring the deployment pipeline for the k8s cluster.  It was noted that the AlertManager pod in pre-production isn't running the AlertManager container.  It constantly restarts.

**To Reproduce**
1. Set your kubectl context to `pre-production`
2. Run `kubectl get pods -n pre-production`
3. At the top of the list you will see the AlertManager pod with lots of restarts and 1/2 containers running within the pod.

**Expected behavior**
All pods should show as running.

**Screenshots**
N/A

**Additional context**
Not so much context but perhaps we consider feature flagging AlertManager for dev and prep as do we actually need it running there at all?

**Comment by Gary-H9** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Cloud-Operations-Team-622a0b371800e400133bb924/issues/ministryofjustice/staff-infrastructure-monitoring-deployments/93?planning-poker) with ZenHub @ASTRobinson @bagg3rs @kyphutruong @mitchdawson1982 @moontune @mTouhid @wanieldilson

**Comment by wanieldilson** [comment]
The logs showed Alertmanager was failing to load the config file, the error:
```
level=error component=configuration msg="Loading configuration file failed" file=/config/alertmanager.yml err="unsupported scheme \"\" for URL"
```

Running `kubectl describe configmap alertmanager-configmap -n pre-productio
n` showed me that some fields that were supposed to be URLs were simply populated with `string`

```yaml
  - name: 'Team PKI'
    slack_configs:
    - api_url: 'string'
      channel: '#mojo-staff-infrastructure-certificate-services-alerts'
      send_resolved: true
      title: '{{ template "slack.alerts.title" . }}'
      text: '{{ template "slack.alerts.text" . }}'
      username: '{{ template "slack.alerts.username" . }}'
      color: '{{ template "slack.alerts.color" . }}'
      icon_emoji: '{{ template "slack.alerts.icon_emoji" . }}'
```

Tracing the variables through to parameter store, I replaced 'string' with a fakeurl that will pass the validation regex.  Re-running the pipeline now to confirm this has fixed the issue.
